filename <- "household_power_consumption.txt"
png(file="plot4.png", width=480, height=480, units="px")
Sys.setlocale("LC_TIME", "en_US")
data <- read.csv(filename, sep=";", na.strings="?", colClasses = "character")
subdata <- data[data$Date == "2/2/2007" | data$Date == "1/2/2007", ]
subdata$Date <- strptime(paste(subdata$Date,subdata$Time), "%d/%m/%Y %H:%M:%S")
subdata$Global_active_power <- as.numeric(subdata$Global_active_power)
subdata$Global_reactive_power <- as.numeric(subdata$Global_reactive_power)
subdata$Voltage <- as.numeric(subdata$Voltage)
subdata$Sub_metering_1 <- as.numeric(subdata$Sub_metering_1)
subdata$Sub_metering_2 <- as.numeric(subdata$Sub_metering_2)
subdata$Sub_metering_3 <- as.numeric(subdata$Sub_metering_3)
par(mfrow=c(2,2))
plot(subdata$Date, subdata$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(subdata$Date, subdata$Voltage, ylab="Voltage", xlab="datetime", type="l")
plot(subdata$Date, subdata$Sub_metering_1, type='l', ylab="Energy sub metering", xlab="")
lines(subdata$Date, subdata$Sub_metering_2, col="red")
lines(subdata$Date, subdata$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=c(1,1), bty="n")
plot(subdata$Date, subdata$Global_reactive_power, ylab="Global_reactive_power", xlab="datetime", type="l")
dev.off()